name: CI

on:
  push:
    branches: [save_rpni_run_example]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Tests
        run: make dc/ci/test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Black Check
        run: make dc/ci/check
